INSERT INTO `ball_bank_area` (`id`, `contry`, `status`, `code`) VALUES ('4', '印度-UPI', '1', '1');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('101', 'MANDIRI', 'MANDIRI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('102', 'BANK BRI', 'BRI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('103', 'BANK BNI', 'BNI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('104', 'BANK BCA', 'BCA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('105', 'BANK UOB INDONESIA', 'BANK_UOB', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('106', 'BANK BRI SYARIAH', 'BRI_SYR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('107', 'BANK DANAMON', 'DANAMON', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('108', 'BANK SYARIAH MANDIRI', 'MANDIRI_SYR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('109', 'PERMATA BANK', 'PERMATA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('110', 'BANK MAYBANK', 'MAYBANK', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('111', 'BANK PANIN', 'PANIN', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('112', 'BANK CIMB NIAGA', 'CIMB', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('113', 'BANK ARTA NIAGA KENCANA', 'ARTA_NIAGA_KENCANA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('114', 'BANK BUANA IND', 'BANK_BUANA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('115', 'BANK LIPPO', 'BANK_LIPPO', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('116', 'BANK NISP', 'OCBC', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('117', 'CITIBANK', 'CITIBANK', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('118', 'JP. MORGAN CHASE BANK', 'JPMORGAN', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('119', 'BANK OF AMERICA', 'BAML', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('120', 'ING INDONESIA BANK', 'BANK_ING', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('121', 'BANK MULTICOR TBK.', 'BANK_MUL', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('122', 'BANK ARTHA GRAHA', 'ARTHA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('123', 'BANK CREDIT AGRICOLE INDOSUEZ', 'BANK_C_AGR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('124', 'THE BANGKOK BANK COMP. LTD', 'BANK_COMP', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('125', 'THE BANK OF TOKYO MITSUBISHI UFJ LTD', 'BANK_TOKYO', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('126', 'BANK SUMITOMO MITSUI INDONESIA', 'MITSUI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('127', 'BANK DBS INDONESIA', 'DBS', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('128', 'BANK RESONA PERDANIA', 'RESONA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('129', 'BANK MIZUHO INDONESIA', 'MIZUHO', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('130', 'STANDARD CHARTERED BANK', 'STANDARD_CHARTERED', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('131', 'BANK ABN AMRO', 'BANK_ABN', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('132', 'BANK KEPPEL TATLEE BUANA', 'BANK_KEPPEL', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('133', 'BANK CAPITAL INDONESIA, TBK.', 'CAPITAL', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('134', 'BANK BNP PARIBAS INDONESIA', 'BNP_PARIBAS', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('135', 'KOREA EXCHANGE BANK DANAMON', 'BANK_DANAMON', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('136', 'RABOBANK INTERNASIONAL INDONESIA', 'RABOBANK', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('137', 'ANZ PANIN BANK', 'PANIN', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('138', 'DEUTSCHE BANK AG.', 'DEUTSCHE', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('139', 'BANK WOORI INDONESIA', 'BANK_WOOR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('140', 'BANK OF CHINA LIMITED', 'BOC', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('141', 'BANK BUMI ARTA', 'BUMI_ARTA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('142', 'BANK ANTARDAERAH', 'BANK_ANTAR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('143', 'BANK HAGA', 'BANK_HAGA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('144', 'BANK IFI', 'BANK_IFI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('145', 'BANK MAYAPADA', 'MAYAPADA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('146', 'BANK DKI', 'DKI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('147', 'BPD DIY', 'DAERAH_ISTIMEWA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('148', 'BANK JATENG', 'BANK_JATENG', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('149', 'BANK JATIM', 'BANK_JATIM', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('150', 'BPD JAMBI', 'JAMBI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('151', 'BPD ACEH', 'ACEH', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('152', 'BANK SUMUT', 'SUMUT', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('153', 'BANK NAGARI', 'BANK_NAGARI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('154', 'BANK RIAU', 'RIAU_DAN_KEPRI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('155', 'BANK SUMSEL', 'SUMSEL_DAN_BABEL', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('156', 'BANK LAMPUNG', 'LAMPUNG', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('157', 'BPD KALSEL', 'BPD_KALSEL', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('158', 'BPD KALIMANTAN BARAT', 'KALIMANTAN_BARAT', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('159', 'BPD KALTIM', 'BPD_KAITIM', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('160', 'BPD KALTENG', 'BPD_KALTENG', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('161', 'BPD SULSEL', 'SULSELBAR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('162', 'BANK SULUT', 'SUMSEL_DAN_BABEL', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('163', 'BPD NTB', 'BPD_NTB', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('164', 'BPD BALI', 'BALI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('165', 'BANK NTT', 'BANK_NTT', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('166', 'BANK MALUKU', 'MALUKU', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('167', 'BPD PAPUA', 'PAPUA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('168', 'BANK BENGKULU', 'BENGKULU', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('169', 'BPD SULAWESI TENGAH', 'SULAWESI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('170', 'BANK SULTRA', 'BANK_SULTRA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('171', 'BANK NUSANTARA PARAHYANGAN', 'NUSANTARA_PARAHYANGAN', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('172', 'BANK SWADESI', 'BANK_SWADESI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('173', 'BANK MUAMALAT', 'MUAMALAT', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('174', 'BANK MESTIKA', 'MESTIKA_DHARMA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('175', 'BANK METRO EXPRESS', 'SHINHAN', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('176', 'BANK MASPION', 'MASPION', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('177', 'BANK HAGAKITA', 'BANK_HAGAKITA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('178', 'BANK GANESHA', 'GANESHA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('179', 'BANK WINDU KENTJANA', 'CCB', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('180', 'BANK HARMONI INTERNATIONAL', 'BANK_HARM', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('181', 'BANK KESAWAN', 'QNB_INDONESIA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('182', 'BANK TABUNGAN NEGARA (PERSERO)', 'BTN', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('183', 'BANK HIMPUNAN SAUDARA 1906, TBK.', 'BANK_HIM', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('184', 'BANK TABUNGAN PENSIUNAN NASIONAL', 'TABUNGAN_PENSIUNAN_NASIONAL', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('185', 'BANK SWAGUNA', 'BANK_SWAGUNA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('186', 'BANK MEGA', 'MEGA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('187', 'BANK BUKOPIN', 'BUKOPIN', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('188', 'BANK BISNIS INTERNASIONAL', 'BISNIS_INTERNASIONAL', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('189', 'BANK BUMIPUTERA', 'BANK_BUMIPUTERA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('190', 'BANK YUDHA BHAKTI', 'BANK_YUDHA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('191', 'BANK MITRANIAGA', 'BANK_MITRAN', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('192', 'BANK AGRO NIAGA', 'AGRONIAGA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('193', 'BANK INDOMONEX', 'BANK_INDOMONEX', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('194', 'BANK ROYAL INDONESIA', 'ROYAL', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('195', 'BANK SYARIAH MEGA', 'MEGA_SYR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('196', 'BANK INA PERDANA', 'BANK_INA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('197', 'PRIMA MASTER BANK', 'PRIMA_MASTER', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('198', 'BANK PERSYARIKATAN INDONESIA', 'BANK_PERSY', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('199', 'BANK AKITA', 'BANK_AKITA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('200', 'BANK DIPO INTERNATIONAL', 'BANK_NOBU', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('201', 'BANK NOBU', 'NATIONALNOBU', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('202', 'BANK KESEJAHTERAAN EKONOMI', 'KESEJAHTERAAN_EKONOMI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('203', 'BANK ARTOS IND', 'ARTOS', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('204', 'BANK PURBA DANARTA', 'BTPN_SYARIAH', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('205', 'BANK MULTI ARTA SENTOSA', 'MULTI_ARTA_SENTOSA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('206', 'BANK MAYORA', 'MAYORA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('207', 'BANK INDEX SELINDO', 'INDEX_SELINDO', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('208', 'BANK VICTORIA INTERNATIONAL', 'BANK_VICTORIA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('209', 'BANK EKSEKUTIF', 'BANK_EKSEK', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('210', 'CENTRATAMA NASIONAL BANK', 'CENTRATAMA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('211', 'BANK FAMA INTERNASIONAL', 'FAMA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('212', 'BANK SINAR HARAPAN BALI', 'MANDIRI_TASPEN', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('213', 'BANK HARDA', 'HARDA_INTERNASIONAL', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('214', 'BANK FINCONESIA', 'BANK_FINCONESIA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('215', 'BANK MERINCORP', 'BANK_MERIN', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('216', 'BANK MAYBANK INDOCORP', 'BANK_MAYBANK', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('217', 'BANK OCBC - INDONESIA', 'OCBC', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('218', 'BANK CHINA TRUST INDONESIA', 'CHINATRUST', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('219', 'BANK COMMONWEALTH', 'COMMONWEALTH', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('220', 'BJB SYARIAH', 'BJB_SYR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('221', 'BANK BCA SYARIAH', 'BCA_SYR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('222', 'BANK BNI SYARIAH', 'BNI_SYR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('223', 'BANK ANDARA', 'OKE', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('224', 'BANK PANIN DUBAI SYARIAH', 'PANIN_SYR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('225', 'BANK HSBC', 'HSBC', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('226', 'BANK SINARMAS', 'SINARMAS_UUS', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('227', 'BANK JABAR BANTEN', 'BANK_JABAR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('228', 'BANK DINAR INDONESIA', 'DINAR_INDONESIA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('229', 'BANK HANA', 'HANA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('230', 'BANK ICBC', 'ICBC', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('231', 'BANK JTRUST', 'JTRUST', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('232', 'BANK EKSPOR INDONESIA', 'EXIMBANK', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('233', 'Bank BCA', 'BCA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('234', 'Bank BJB', 'BJB', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('235', 'BANK BNI 46', 'BNI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('236', 'BANK OF CHINA LIMITED', 'BOC', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('237', 'Bank BRI', 'BRI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('238', 'Bank BTN', 'BTN', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('239', 'BANK WINDU KENTJANA', 'CCB', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('240', 'BANK DBS INDONESIA', 'DBS', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('241', 'BPD DKI JAKARTA', 'DKI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('242', 'BPD ACEH', 'ACEH', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('243', 'BPD BALI', 'BALI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('244', 'BANK OF AMERICA', 'BAML', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('245', 'Bank BTPN', 'BTPN', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('246', 'BANK CIMB NIAGA', 'CIMB', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('247', 'BANK FAMA INTERNASIONAL', 'FAMA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('248', 'BANK HANA', 'HANA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('249', 'BANK HSBC', 'HSBC', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('250', 'BANK ICBC', 'ICBC', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('251', 'BANK MEGA', 'MEGA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('252', 'BANK OCBC NISP', 'OCBC', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('253', 'BANK ARTHA GRAHA', 'ARTHA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('254', 'BPD JAMBI', 'JAMBI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('255', 'BANK PANIN', 'PANIN', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('256', 'BPD PAPUA', 'PAPUA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('257', 'BANK ROYAL INDONESIA', 'ROYAL', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('258', 'BANK SUMUT', 'SUMUT', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('259', 'BANK JTRUST', 'JTRUST', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('260', 'BANK MALUKU', 'MALUKU', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('261', 'BANK MAYORA', 'MAYORA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('262', 'BANK SUMITOMO MITSUI INDONESIA', 'MITSUI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('263', 'BANK MIZUHO INDONESIA', 'MIZUHO', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('264', 'BANK RESONA PERDANIA', 'RESONA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('265', 'BANK BCA SYARIAH', 'BCA_SYR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('266', 'BJB SYARIAH', 'BJB_SYR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('267', 'BANK BNI SYARIAH', 'BNI_SYR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('268', 'BPD NTB', 'BPD_NTB', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('269', 'BANK BRI SYARIAH', 'BRI_SYR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('270', 'BANK BUKOPIN', 'BUKOPIN', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('271', 'BANK CAPITAL INDONESIA, TBK.', 'CAPITAL', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('272', 'BANK DANAMON INDONESIA', 'DANAMON', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('273', 'BANK GANESHA', 'GANESHA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('274', 'BANK LAMPUNG', 'LAMPUNG', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('275', 'BANK MANDIRI', 'MANDIRI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('276', 'BANK MASPION', 'MASPION', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('277', 'BANK MAYBANK INDONESIA', 'MAYBANK', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('278', 'BANK PERMATA', 'PERMATA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('279', 'BANK METRO EXPRESS', 'SHINHAN', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('280', 'BANK ABN AMRO', 'BANK_ABN', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('281', 'BANK HIMPUNAN SAUDARA 1906, TBK.', 'BANK_HIM', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('282', 'BANK IFI', 'BANK_IFI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('283', 'BANK INA PERDANA', 'BANK_INA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('284', 'ING INDONESIA BANK', 'BANK_ING', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('285', 'BANK MULTICOR TBK.', 'BANK_MUL', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('286', 'BANK NTT', 'BANK_NTT', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('287', 'BANK UOB INDONESIA', 'BANK_UOB', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('288', 'BANK BENGKULU', 'BENGKULU', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('289', 'CITIBANK', 'CITIBANK', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('290', 'DEUTSCHE BANK AG.', 'DEUTSCHE', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('291', 'BANK EKSPOR INDONESIA', 'EXIMBANK', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('292', 'JP. MORGAN CHASE BANK', 'JPMORGAN', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('293', 'BANK MAYAPADA', 'MAYAPADA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('294', 'BANK SYARIAH MEGA', 'MEGA_SYR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('295', 'BANK MUAMALAT INDONESIA', 'MUAMALAT', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('296', 'BANK ANDARA', 'OKE', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('297', 'RABOBANK INTERNASIONAL INDONESIA', 'RABOBANK', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('298', 'BANK SINARMAS', 'SINARMAS', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('299', 'BPD SULAWESI TENGAH', 'SULAWESI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('300', 'BANK AGRO NIAGA', 'AGRONIAGA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('301', 'THE BANGKOK BANK COMP. LTD', 'BANK_COMP', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('302', 'BANK HAGA', 'BANK_HAGA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('303', 'BANK HARMONI INTERNATIONAL', 'BANK_HARM', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('304', 'BANK DIPO INTERNATIONAL', 'BANK_NOBU', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('305', 'BANK WOORI INDONESIA', 'BANK_WOOR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('306', 'BANK BUMI ARTA', 'BUMI_ARTA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('307', 'BANK PANIN DUBAI SYARIAH', 'PANIN_SYR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('308', 'BANK AKITA', 'BANK_AKITA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('309', 'BANK ANTARDAERAH', 'BANK_ANTAR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('310', 'BANK BUANA IND', 'BANK_BUANA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('311', 'BANK CREDIT AGRICOLE INDOSUEZ', 'BANK_C_AGR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('312', 'BANK EKSEKUTIF', 'BANK_EKSEK', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('313', 'BANK JABAR BANTEN', 'BANK_JABAR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('314', 'BANK JATIM', 'BANK_JATIM', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('315', 'BANK LIPPO', 'BANK_LIPPO', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('316', 'BANK MERINCORP', 'BANK_MERIN', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('317', 'BANK PERSYARIKATAN INDONESIA', 'BANK_PERSY', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('318', 'THE BANK OF TOKYO MITSUBISHI UFJ LTD', 'BANK_TOKYO', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('319', 'BANK YUDHA BHAKTI', 'BANK_YUDHA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('320', 'BPD KALTIM', 'BPD_KAITIM', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('321', 'BPD KALSEL', 'BPD_KALSEL', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('322', 'CENTRATAMA NASIONAL BANK', 'CENTRATAMA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('323', 'BANK CHINA TRUST INDONESIA', 'CHINATRUST', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('324', 'BANK JATENG', 'BANK_JATENG', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('325', 'BANK KEPPEL TATLEE BUANA', 'BANK_KEPPEL', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('326', 'BANK MITRANIAGA', 'BANK_MITRAN', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('327', 'BANK NAGARI', 'BANK_NAGARI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('328', 'BANK SULTRA', 'BANK_SULTRA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('329', 'BANK BNP PARIBAS INDONESIA', 'BNP_PARIBAS', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('330', 'BPD KALTENG', 'BPD_KALTENG', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('331', 'BANK SYARIAH MANDIRI', 'MANDIRI_SYR', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('332', 'KOREA EXCHANGE BANK DANAMON', 'BANK_DANAMON', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('333', 'BANK MAYBANK INDOCORP', 'BANK_MAYBANK', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('334', 'BANK SWADESI', 'BANK_SWADESI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('335', 'BANK SWAGUNA', 'BANK_SWAGUNA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('336', 'BANK COMMONWEALTH', 'COMMONWEALTH', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('337', 'BANK JASA JAKARTA', 'JASA_JAKARTA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('338', 'BANK NOBU', 'NATIONALNOBU', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('339', 'PRIMA MASTER BANK', 'PRIMA_MASTER', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('340', 'BANK SINARMAS', 'SINARMAS_UUS', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('341', 'BANK HAGAKITA', 'BANK_HAGAKITA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('342', 'BANK VICTORIA INTERNATIONAL', 'BANK_VICTORIA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('343', 'BANK INDEX SELINDO', 'INDEX_SELINDO', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('344', 'BANK KESAWAN', 'QNB_INDONESIA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('345', 'BANK INDOMONEX', 'BANK_INDOMONEX', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('346', 'BANK SINAR HARAPAN BALI', 'MANDIRI_TASPEN', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('347', 'BANK MESTIKA', 'MESTIKA_DHARMA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('348', 'BANK RIAU', 'RIAU_DAN_KEPRI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('349', 'BANK BUMIPUTERA', 'BANK_BUMIPUTERA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('350', 'BANK FINCONESIA', 'BANK_FINCONESIA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('351', 'BPD DIY', 'DAERAH_ISTIMEWA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('352', 'BANK DINAR INDONESIA', 'DINAR_INDONESIA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('353', 'BPD KALIMANTAN BARAT', 'KALIMANTAN_BARAT', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('354', 'BANK SULUT', 'SUMSEL_DAN_BABEL', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('355', 'BANK ARTA NIAGA KENCANA', 'ARTA_NIAGA_KENCANA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('356', 'BANK MULTI ARTA SENTOSA', 'MULTI_ARTA_SENTOSA', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('357', 'STANDARD CHARTERED BANK', 'STANDARD_CHARTERED', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('358', 'BANK HARDA', 'HARDA_INTERNASIONAL', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('359', 'BANK BISNIS INTERNASIONAL', 'BISNIS_INTERNASIONAL', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('360', 'BANK EKONOMI', 'KESEJAHTERAAN_EKONOMI', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('361', 'BANK NUSANTARA PARAHYANGAN', 'NUSANTARA_PARAHYANGAN', '4');
INSERT INTO `ball_bank` (`id`, `bank_cname`, `bank_code`, `area_id`) VALUES ('362', 'BANK TABUNGAN PENSIUNAN NASIONAL', 'TABUNGAN_PENSIUNAN_NASIONAL', '4');
