server:
  port: 10100
  cache:
    type: redis
#静态资源路径
static:
  file: "file:/usr/ball_project/ball_web/upload/"
#  file: "classpath:static"
spring:
  #设置单个文件的大小，默认1MB
  servlet:
    multipart:
      #单个文件大小
      max-file-size: 20MB
      #一次请求总大小
      max-request-size: 50MB
  thymeleaf:
    mode: LEGACYHTML5
    prefix: classpath:/templates/
  datasource:
    druid:
      #TODO 配置mysql
#      url: "jdbc:mysql://192.168.101.33:3306/ball?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true"
#      username: "wx_ser"
#      url: "jdbc:mysql://192.168.101.33:3306/vx?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8"
      url: "jdbc:mysql://192.168.101.33:3306/shiro?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8"
#      url: "jdbc:mysql://192.168.101.33:3306/ball1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8"
#      url: "jdbc:mysql://192.168.101.33:3306/ball_cha?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8"
#      url: "jdbc:mysql://47.241.62.70:3306/game?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8"
#      username: "vx"
#      password: "123123"
      username: "shiroshiro"
      password: "zp4JiweJ7EF6pE42"
#      username: "ball1"
#      password: "ball1@123123"
#      username: "game"
#      password: "ApW4RfEFGHk2itrh"
#      username: "ball_cha"
#      password: "pLbGnHfKTaai5xKz"
      driver-class-name: com.mysql.cj.jdbc.Driver
      #连接池配置
      min-idle: 5
      initial-size: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      remove-abandoned: true
      remove-abandoned-timeout: 120
      log-abandoned: true
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #监控
      filter:
        wall:
          enabled: true
          config:
            multi-statement-allow: true
  redis:
    database: 0
    #TODO 配置redis
#    host: 47.241.62.70
    host: 192.168.101.33
#    host: 127.0.0.1
    port: 6379
    timeout: 3000ms
#    password: wy011620.
  #
logging:
  level:
    root: info
    com.oxo.ball.mapper: debug
some-comfig:
  server-url: 'http://127.0.0.1:10100/'
#  time-zone: "Africa/Accra"
  api-key: "b7c0d664a71b77ed3124268f330fece5"
  api-bookmaker: 1
  api-switch: 0
  #对接支付地址 478794054
  pay-url: "http://8.136.97.179:7777/"
  #服务器地址，用于接收支付回调
  pay-callback-url: "http://8.136.97.179:7777/"
  #解密私钥
  pay-private-key: "MIIEpAIBAAKCAQEAy3My0diBGfkjFzq5UVl0SeOLSg/Lcmvhl9hEuRr6B7O7KV7ghYCQR2tJcfrZQ1ehqPVS1jskNkoXKXfcAzeEgQrcFLYMVwuHVh2mu8imUoKY7fkearU6MtJHi2bpxownZLJzurbzbeeWiZWj05HzCZVPjfAhxkTdC+kuZBJfF0Fc6xrlXgbDslsEyEyKIGku7G47ZRmtJjDiUk+Bec7f9uhTbSWWu4ZO57S4fuA5K1qXf0Tmw6fEiM5DRkfYGsmO+2x6AmHGwVhFw37k/UEpur3bkajK9fk3s6xtJjmLet3y+g6jcdpPMr+sZdMFxfGhIqu0xPy2mNNZmANJni3/PQIDAQABAoIBAA8LL6DQr4sqHuwizX00biLgjnYlgNevHnlJ5psBYaecJKTEfTmh7gk5565j7BjMrAmASmXI7b6N7/SDBmO+gS/Bi9CEPZlaIuG9Q4zzI0lKmuBN4W/mgq0rW1r1eyfRSUBq6Z/O02U3EKyPwhNs4Vm+DqniLb0pbmbpESMZMKrZaqXSRMQHfwp7wx8W+3dPEQAs3pO1SwEpfL8Sbx/gBaRUi5iVIjG52G7daoCCGAPzyzhGtKNkc/Yff9dnI7hGwS2/zysrOychDSKJ+/XGlQb9Zwp8F7bz84wm3BACTCCjzvGd5NxIZqXoeR8VZ9LWpJSlRIMIskExhlp/hFfZtckCgYEA8Vc/m8frL879ioxSkbcaFYDuvS0FFbAZWh9z2XTJGgSWQlQ0Ms5kU/668c7VXOlLrbUQrvH+aAp4uok+o+hlZNTbFJhRXs2igfIKpC4Ak8tYkbrsxmpJgP9/LScLlgTmrrFSo6ADJU0oPSpC95HwvwyIao9fpauhFYZtBf5s7o8CgYEA187DYOuRbmHKbYLCXe37grEGerOz4WUpSWkaFmlwZ14T8i/U0ps/qRiiOOdfrEnjAT3LJkZ1GL0fBLqN2KAkD7XjcOECcVYQMN/5qwEys9udmbgj+I0u5RSeE8mYB0RP06/qCg8NocxH7Z5STjd3JA1gZwl974uwcN1mkdduW3MCgYEAyUOXmlRowCAAtRA8s6RdLl2tuznWKbYIDm54cHrCUt5MaNhMB6qzZJDkWk/BA5DTOfPsC9ln7l/9OqLGCG8AT8xrP4ufIE6hHXk6gpySgq5sGGwolXeCAQARkRgkw2Em97yNTENfHDZyPkAGROwCN3E+Oo+ClmjBF3BZb0w0j+UCgYA5Y46pc3uVMwQ14xP1DphXxOPINYmcYt572ytI0nlFw8riGL4r04U2XoqlP0I9+tgXOGuRniL9lS1ugH3AIbX1R5VYKz4PDaf4l1c5lnP5SGm8uy81pbXWzYjMEkwPgqcH0DwYuLATWtO16OhSTIWuXLBKNkf7L9aX7QiduABs6QKBgQCU6GhHoaIPAvVaMCm+sdT8MwH6ThH3a+kWqFj3AgkUBSv9UUhYQ+A6Qey+AcRpKVP91z82noHucakJ/7EMTOnsnLK8mjrFak+L2GZWrPhk2bMZnF7vxGHuFcVT4XWqDGY3GwdDTfX0WcJGtjyLJkD05ldO74jNYXVvIZvyN0abLw=="
  #加密公钥
  pay-public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoEixcgAPmLpHLEDh3P8eGpxolNbGJoxbrNQU1kaRCTMiu5qTaLJsTb6SVh7J4yztLOSdvIwbC2YeyVW8fatx3eQ4RX6/txdtm07ov1bmC9n6/caOeRz2Pq2ZOse3uFuSjpQbF/2oAv3E6zWq5tdHwG89ZNj+igs5lme4S6Uy2OE2MsqV/kwGMdBcdTOld8ki3MTsoEeBg9+IoqRD6gqil9sZdoHf0ItVE85Rw2Gp1rMfeTUMW7W3SvKItB33978/PgVmUvKLwY9+xsvWmILBZgkIMjUZ9/98LsyhdOvElcWFkYX2f84PSIJ8roAJhUpGJnw05i1jykDM6wa3sZ051wIDAQAB"
  #短信平台接口地址
  sms-server: '---http://api.quanqiusms.com/api/sms/mtsend'
  #短信平台appkey
  sms-app-key: '---r8mAe221'
  #短信平台secretKey
  sms-secret-key: '---XsyJzx422'
  #短信验证码,{0}为验证码参数，必须
  sms-message: 'Your verification code is {0}, please ignore this message unless you operate by yourself'
  #前端访问地址，拼接邀请码，不需要了
#  invitation-url: "http://localhost:9527/?code="
#    - 72
#    - 269
#    - 673
# update ball_game set start_time=start_time+86400000,game_status=1 where game_status=2;
# wy011620.
# eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOlsiNyIsIjE2NTMxMjIzMTQwMDMiXX0.cwnL6ELGa83gftRJGe3XIGJioDXergYdR927O9YGwRE
# 短信平台 http://www.quanqiusms.com/
#
#